[target.'cfg(target_os = "windows")']
rustflags = ["-C", "target-feature=+crt-static"]

[target.'cfg(target_os = "windows")'.env]
VCPKG_ROOT = "D:\\vcpkg"
VCPKG_DEFAULT_TRIPLET = "x64-windows-static"
LIBHEIF_NO_PKG_CONFIG = "1"
LIBHEIF_STATIC = "1"
LIBHEIF_USE_STATIC_LIB = "1"

[target.'cfg(target_os = "macos")'.env]
PKG_CONFIG_PATH = "/opt/homebrew/lib/pkgconfig"